sudo: required
dist: trusty
language: python
python:
  - "3.5"
install:
  - sudo apt-get update --fix-missing
  - sudo apt install swig build-essential tk-dev libncurses5-dev libncursesw5-dev libreadline6-dev libdb5.3-dev
    libgdbm-dev libsqlite3-dev libssl-dev libbz2-dev libexpat1-dev liblzma-dev zlib1g-dev libssl-dev libffi-dev
    python-dev python3-dev python3-pip sox libsox-fmt-all flac portaudio19-dev pulseaudio libpulse-dev
  - chmod +x .travis_scripts/install.sh
  - ./.travis_scripts/install.sh
  - pip3 install -U pytest
  - pip3 install -U pep8
script:
  - pep8 main --ignore E501 --exclude=main/hotword_engine/snowboy_detector.py
  - python3 -m pytest tests/
